steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:latest', './spring-boot-hello']

# Build the Spring Boot Worker container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:latest', './spring-boot-worker']

# Push the Hello World container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:latest']

# Push the Worker container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['services', 'enable', 'run.googleapis.com', 'artifactregistry.googleapis.com', 'pubsub.googleapis.com', 'compute.googleapis.com', '--project', '$PROJECT_ID']

- id: 'tf-init'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      terraform init

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      export TF_VAR_commit_sha=$COMMIT_SHA
      terraform plan

- id: 'tf-apply'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      export TF_VAR_commit_sha=$COMMIT_SHA
      terraform apply -auto-approve
