steps:
- id: 'build-hello'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:latest', './spring-boot-hello']
  waitFor: ['-']

# Build the Spring Boot Worker container image
- id: 'build-worker'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:latest', './spring-boot-worker']
  waitFor: ['-']

# Push the Hello World container image
- id: 'push-hello'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:$COMMIT_SHA']
  waitFor: ['build-hello']

- id: 'push-hello-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-hello:latest']
  waitFor: ['build-hello']

# Push the Worker container image
- id: 'push-worker'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:$COMMIT_SHA']
  waitFor: ['build-worker']

- id: 'push-worker-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spring-boot-worker:latest']
  waitFor: ['build-worker']

- id: 'tf-init'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      terraform init
  waitFor: ['-']

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      export TF_VAR_commit_sha=$COMMIT_SHA
      export TF_VAR_project_id=${_TF_VAR_PROJECT_ID}
      export TF_VAR_compute_service_account=${_TF_VAR_COMPUTE_SERVICE_ACCOUNT}
      export TF_VAR_region=${_TF_VAR_REGION}
      export TF_VAR_aws_access_key_id=${_TF_VAR_AWS_ACCESS_KEY_ID}
      export TF_VAR_aws_secret_access_key=${_TF_VAR_AWS_SECRET_ACCESS_KEY}
      export TF_VAR_aws_region=${_TF_VAR_AWS_REGION}
      terraform plan
  waitFor: ['tf-init']

- id: 'tf-apply'
  name: 'hashicorp/terraform:1.5.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/gcp
      export TF_VAR_commit_sha=$COMMIT_SHA
      export TF_VAR_project_id=${_TF_VAR_PROJECT_ID}
      export TF_VAR_compute_service_account=${_TF_VAR_COMPUTE_SERVICE_ACCOUNT}
      export TF_VAR_region=${_TF_VAR_REGION}
      export TF_VAR_aws_access_key_id=${_TF_VAR_AWS_ACCESS_KEY_ID}
      export TF_VAR_aws_secret_access_key=${_TF_VAR_AWS_SECRET_ACCESS_KEY}
      export TF_VAR_aws_region=${_TF_VAR_AWS_REGION}
      terraform apply -auto-approve
  waitFor: ['tf-plan', 'push-hello', 'push-worker', 'push-hello-latest', 'push-worker-latest']

substitutions:

  _TF_VAR_PROJECT_ID: "REPLACE_ME"
  _TF_VAR_COMPUTE_SERVICE_ACCOUNT: "REPLACE_ME"
  _TF_VAR_REGION: "us-central1"
  _TF_VAR_AWS_ACCESS_KEY_ID: "REPLACE_ME"
  _TF_VAR_AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
  _TF_VAR_AWS_REGION: "eu-west-1"
